<a href="https://colab.research.google.com/github/jsunh98/computervision/blob/main/computervisiontutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)
print(tensor_zero_d)


tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_zero_d = tf.constant([2,0,-3, 8, 90])
print(tensor_zero_d)


tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int32)


In [ ]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [ ]:
tensor_three_d = tf.constant([
    [[1,2,0],
    [3,5,-1]],
    [[10,2,0],
    [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
    [4,-3,32]],
])
print(tensor_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [ ]:
import tensorflow as tf
tensor_four_d = tf.constant([
[
    [[1,2,0],
    [3,5,-1]],
    [[10,2,0],
    [1,0,2]],
    [[5,8,0],
     [2,7,0]],
    [[2,1,9],
    [4,-3,32]],
],
[
    [[11,22,30],
    [6,4,1]],
    [[12,3,6],
    [8,23,21]],
    [[57,4,2],
     [6,17,60]],
    [[7,3,10],
    [7,-3,31]],
],
[
    [[11,12,10],
    [36,57,-12]],
    [[17,12,40],
    [9,0,3]],
    [[51,18,6],
     [5,57,50]],
    [[28,81,89],
    [42,-9,-2]],
],
])
print(tensor_four_d)

tf.Tensor(
[[[[  1   2   0]
   [  3   5  -1]]

  [[ 10   2   0]
   [  1   0   2]]

  [[  5   8   0]
   [  2   7   0]]

  [[  2   1   9]
   [  4  -3  32]]]


 [[[ 11  22  30]
   [  6   4   1]]

  [[ 12   3   6]
   [  8  23  21]]

  [[ 57   4   2]
   [  6  17  60]]

  [[  7   3  10]
   [  7  -3  31]]]


 [[[ 11  12  10]
   [ 36  57 -12]]

  [[ 17  12  40]
   [  9   0   3]]

  [[ 51  18   6]
   [  5  57  50]]

  [[ 28  81  89]
   [ 42  -9  -2]]]], shape=(3, 4, 2, 3), dtype=int32)


In [ ]:
import numpy as np
np_array = np.array([1,2,4])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int64)


In [ ]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(2, 5, 5), dtype=float32)
